---
title: "Basics of Probability"
author: "D. L. Burrell"
date: "27/06/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Rules of probability

The first lesson assumes that you are familiar with common probability notation and the basic probability rules. For reference, we review these things here. 

Probabilities are defined for events. An event is an outcome that could potentially or hypothetically be observed or experiences. Typical, but seemingly meaningless examples that are often given include the result of tossing a fair coin, the result of rolling a fair six-sided die, the result of drawing three cards from a standard deck of 52 cards, 13 from each of 4 suits. To make the examples more meaningful, consider the result, in terms of incidence of crown rot, of growing five wheat seedlings in a pot inoculated with fusarium culmorum, or the result, in terms of protein yield, of growing a new wheat cultivar that has been selectively bred for higher levels of protein in the grain. All of these are events. In mathematical notation, we often write an event as a capital letter, for example, we might let $A$ denote the event that all five seedlings in the inoculated pot develop symptoms of crown rot after a given growth period. We do not know the probability of this occuring, but suppose it is some value $p$, then we would write $P(A)=p$. Typically, we represent the numerical result of an experiment as a random variable $X$. Therefore, we might let $X$ be the number of infected plants in a pot (out of 5 planted) after a given growth period. Then we write $P(X=5)=p$. 

Probabilities must be between zero and one, i.e., $0\leq P(A)\leq 1$ for any event $A$. 

Probabilities add to one, i.e., if we add up the probabilities of all possible events, those probabilities must add to one. For the inoculated seedlings in a pot example:
$$
\sum_{i=1}^5 P(X=i)=1.
$$

Recall that the symbol $\sum_{i=1}^5$ denotes adding up the entries as $i$ counts up from 1 to 6. 

The complement of an event, $A^\prime$, means that the event does not happen. Since probabilities must add to one, 